{{- if and (.Values.oidc.enabled) (not (.Values.oidc.secret.useExistingSecret)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "skooner.oidcSecretName" . }}"
  labels:
    {{- include "skooner.labels" . | nindent 4 }}
data:
  OIDC_CLIENT_ID: "{{ .Values.oidc.secret.clientId | b64enc }}"
  OIDC_SECRET: "{{ .Values.oidc.secret.clientSecret | b64enc }}"
{{- end -}}
