apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy-config
data:
  conf.yml: |
    pageInfo:

    appConfig:
      hideComponents:
        hideSearch: true
        hideHeading: true
        hideNav: true
        hideSettings: true
        hideFooter: true
      preventWriteToDisk: true
      showSplashScreen: true
      enableServiceWorker: true
      statusCheck: true
      statusCheckInterval: 60
      colCount: 2
      theme: colorful
      fontAwesomeKey: c94dc2b452
      layout: sidebar
      iconSize: large
    sections:
    - name: Host
      icon: mdi-penguin
      displayData:
        collapsed: false
        cols: 1
      widgets:
      - type: clock
      # - type: public-ip

    - name: Applications
      icon: mdi-kubernetes
      sortBy: alphabetical
      cutToHeight: true
      items:
      - title: K8s dashboard
        icon: hl-kubernetes-dashboard
        url: https://dash.localtest.me
        description: unsecure
        statusCheckUrl: http://kubernetes-dashboard.kubernetes-dashboard:8080/health
        tags: [hosted, kubernetes, dashboard]

      - title: Traefik
        icon: hl-traefik
        description: unsecure
        url: https://traefik.localtest.me/dashboard/
        statusCheckUrl: http://traefik.kube-system:9000/ping
        tags: [hosted, traefik, dashboard]

      - title: Minio
        icon: hl-minio
        url: https://minio.localtest.me
        description: minio/minioadmin
        statusCheckUrl: http://minio.storage:9000/minio/health/live
        tags: [hosted, traefik, dashboard]

      - title: Code
        icon: hl-vscode
        url: https://code.localtest.me
        description: unsecure
        statusCheckUrl: http://code-server-user.default/healthz
        tags: [hosted, traefik, dashboard]

      - title: Prometheus
        icon: hl-prometheus
        url: https://prometheus.localtest.me
        description: unsecure
        statusCheckUrl: http://prometheus-server.monitoring/-/healthy
        tags: [hosted, prometheus, dashboard]

      - title: Grafana
        icon: hl-grafana
        url: https://grafana.localtest.me
        description: unsecure
        statusCheckUrl: http://grafana.default/healthz
        tags: [hosted, traefik, dashboard]

      # pushgateway.localtest.me

    - name: Latest CVE vulnerabilities
      displayData:
          collapsed: true
      widgets:
      - type: cve-vulnerabilities
        useProxy: true