apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dashy.fullname" . }}
  labels:
    {{- include "dashy.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dashy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: "{{ include "dashy.configmap" . | sha256sum }}"
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dashy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dashy.serviceAccountName" . }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe: 
            tcpSocket:
              port: 80
            initialDelaySeconds: 2 #Default 0 
            periodSeconds: 2 #Default 10 
            timeoutSeconds: 1 #Default 1 
            successThreshold: 1 #Default 1 
            failureThreshold: 3 #Default 3              
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          volumeMounts:
            - name: dashy-config
              mountPath: /app/public/
      volumes:
        - name: dashy-config
          configMap:
            name: dashy-config
